### ISSUE TITLE
Use * match will echo some error.

### ISSUE THREAD

**Issue by bstaint** [Shougo/unite-outline#46]
use * match will echom:
```
Error detected while processing /root/.vim/bundle/unite.vim/autoload/unite.vim:
line  205:
E127: Cannot redefine function unite#redraw: It is in use
```
![sn](https://cloud.githubusercontent.com/assets/5853792/7181860/383693c6-e480-11e4-9e08-8429231ea686.png)

**Comment by Shougo** [comment]
It is not unite-outline error.

Please read issue template and create issue in unite.vim.
