### ISSUE TITLE
Problem with using outline for viml

### ISSUE THREAD

**Issue by blakesweeney** [Shougo/unite-outline#50]
When I open an outline in a vim file I get the follow error when I enter insert mode to filter:

```
Error detected while processing function unite#handlers#_on_cursor_moved_i..<SNR>159_check_redraw..unite#redraw..unite#view#_redraw..unite#candidates#_recache..<SNR>15
0_recache_candidates_loop..unite#helper#call_source_filters..unite#helper#call_filter..117..<SNR>147_List_mark:
line    7:
E121: Undefined variable: v:val
```

this doesn't happen for me when using this in python.

**Comment by Shougo** [comment]
I cannot reproduce the problem.  It seems Vim's bug.
Please update your Vim version.

My Vim version: 7.4.688

**Comment by blakesweeney** [comment]
I think it is a bad interaction with another plugin I had. Probably gorodinskiy/vim-coloresque. When I don't use it this issue disappears. It is not essential to me so I just won't use it.

**Comment by Shougo** [comment]
OK.
