### ISSUE TITLE
unite-outline does not extract pure virtual functions

### ISSUE THREAD

**Issue by ompugao** [Shougo/unite-outline#53]
unite-outline: commit 0686316
unite: e50621a

https://gyazo.com/f28bcc366af9df21f54ad88d7951d495
![img](https://i.gyazo.com/f28bcc366af9df21f54ad88d7951d495.png)

**Comment by Shougo** [comment]
I think it is ctags feature.
But, ctags may support it.
Please check ctags arguments.

**Comment by Shougo** [comment]
http://sourceforge.net/p/ctags/bugs/200/

Hm....

**Comment by Shougo** [comment]
Fixed.

**Comment by ompugao** [comment]
thanks a lot!
