### ISSUE TITLE
error message print when open vim but no file opened

### ISSUE THREAD

**Issue by wuxinxinggg** [Shougo/unite-outline#54]
[unite.vim] function unite#view#_set_syntax..unite#helper#call_hook..<SNR>166_Source_Hooks_on_syntax, line 3
[unite.vim] Vim(if):E121: Undefined variable: state
[unite.vim] Error occurred in calling hook "on_syntax"!
[unite.vim] Source name is outline
Press ENTER or type command to continue

**Comment by Shougo** [comment]
Fixed.
