### ISSUE TITLE
Annoying errors when update via neobundle

### ISSUE THREAD

**Issue by zdm** [Shougo/unite-outline#57]
Hello.

Every time, when I try to update vim plugins with command:
```
 Unite -log -wrap neobundle/update:all
```
I get the following error for unite-outline:

![screenshot 2015-10-09 09 15 37](https://cloud.githubusercontent.com/assets/1025608/10387110/1f0485e0-6e67-11e5-956f-5bf752c962d0.png)

This error occurred only under linux, on windows everything is ok.

**Comment by Shougo** [comment]
Please reinstall unite-outline by `:NeoBundleReinstall unite-outline`.
