### ISSUE TITLE
特定の形式の候補が表示されない

### ISSUE THREAD

**Issue by YoshihiroIto** [Shougo/unite-outline#58]
特定の形式の候補が表示されない問題になりました。

MacVimKaoriya パッチ891
unite,unite-outline,vimprocそれどれ最新にアップデートしています。

手元にあるファイルの内unite-outlineで対応しているファイルで試してみた結果を下記にまとめます。

候補が表示される形式
.vim
.go
.lua
.md

候補が表示されない形式
.cs
.cpp

**Comment by Shougo** [comment]
こちらでもテストしたいと思います。
サンプルファイルをアップロードしてもらえますか。

**Comment by YoshihiroIto** [comment]
https://gist.github.com/YoshihiroIto/1e6d22fabf3846814b91
に.csと.cppを添付しました。
よろしくお願いします。

**Comment by Shougo** [comment]
とりあえず試してみたんですが、どちらも普通に動作しますね……
ctags にパスが通っていないような気がします。 確認してください。
それでもダメなら、最小構成の .vimrc を用意してください。

**Comment by YoshihiroIto** [comment]
失礼しました。
ステータスバーに「Sorry, Exuberant Ctags required.」と表示されていました。

ただしこの環境にはctagsは導入済みでvimshellでctagsは実行できる状態です。
したがってパスも通っていると思います。

もう少し探ってみます。

**Comment by Shougo** [comment]
ctags --version の結果をアップロードしてください。
unite-outline は ctags --version の結果をチェックしているのです。

**Comment by YoshihiroIto** [comment]
起動しているctags は --versionがないらしくエラーになっていました。

```
~/> ctags --version
!!!/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -!!!
!!!usage: ctags [-BFadtuwvx] [-f tagsfile] file ...!!!
!!!vimshell: exit 1 "ctags --version"!!!
```

MacVimKaoriya添付のctagsが優先されるべきところが、
Xcode側のctagsが起動されているのが問題っぽいでした。

やはり、自分の環境の問題っぽいですね。
以前は動いていたので、何かが狂ってしまったようです。
失礼しました。

**Comment by YoshihiroIto** [comment]
パスの設定を書き換えて無事動作することを確認しました。

お騒がせしてしまって失礼しました。

**Comment by Shougo** [comment]
なるほど。こういうこともあるんですね……
