### ISSUE TITLE
can not work in neovim

### ISSUE THREAD

**Issue by jjwt** [Shougo/unite-outline#60]
my options in ~/.config/nvim/init.vim

    NeoBundleFetch 'Shougo/neobundle.vim'
    "NeoBundle 'Shougo/vimproc' "{{{3
    NeoBundle 'Shougo/vimproc', { 
        \ 'build' : {
        \     'windows' : 'tools\\update-dll-mingw',
        \     'cygwin' : 'make -f make_cygwin.mak',
        \     'mac' : 'make -f make_mac.mak',
        \     'unix' : 'make -f make_unix.mak',
        \    },
        \ }  "}}}3
    NeoBundle 'Shougo/unite.vim' 
    NeoBundle 'Shougo/unite-help'
    NeoBundle 'tacroe/unite-mark'
    NeoBundle 'Shougo/deoplete.nvim'
    NeoBundle 'Shougo/unite-outline'
    if neobundle#tap('unite-outline') "{{{4
    nnoremap <silent> <leader>fo :<C-u>Unite -vertical outline<CR>
    endif
    "}}}4

as above , unite.vim unite-mark deoplete.nvim all works except unite-outline

When i press \<leader\>fo, errmsg is:

    [unite.vim] Invalid source name "outline" is detected.
    [unite.vim] unite.vim: Invalid source

to make sure it installed, i input command:

    neobundle#tap('unite-outline')

it echo 1. As a result, what should i do to make it work ?

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please create minimal init.vim without neobundle.
I will test it.

**Comment by Shougo** [comment]
The unite-outline is installed correctly?
I recommend you to reinstall it.

**Comment by jjwt** [comment]
I cd to the bundle directory, and excute command

    rm -rf NeoBundle.lock unite-outline neobundle.vim .neobundle 

This make nvim reinstall outline after restarting, and it works!
Sorry for wasting your time and many thanks!
