### ISSUE TITLE
Error detected while processing function unite#view#_set_syntax

### ISSUE THREAD

**Issue by learningjs** [Shougo/unite-outline#65]
Just installed Unite and this plugin, I get:

>Error detected while processing function unite#view#_set_syntax:                                                                              
>line   45:                                                                                                                                    
>E731: using Dictionary as a String                                                                                                            
>E412: Not enough arguments: ":highlight link uniteSource__Outline"

and I can not figure out what is the source :)

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please upload minimal .vimrc less than 20 lines and reproduce ways from Vim starting.

**Comment by learningjs** [comment]
Thank you for your reply.

I have found the cause, I had this offending line in the config file (I am using nvim / init.vim):

```
let g:unite_abbr_highlight = {}
```

**Comment by Shougo** [comment]
OK
