### ISSUE TITLE
The comments who start with # in markdown code blocks are considered as a headings

### ISSUE THREAD

**Issue by KabbAmine** [Shougo/unite-outline#66]
In code blocks in markdown files, if an instruction starts with `#` it will be considered being a heading.

![md](https://cloud.githubusercontent.com/assets/5658084/13459229/609f4290-e083-11e5-8d9c-5e915280c4d0.png)

A workaround to prevent that is to add a space before the comment:

```
    ```sh
     # A comment
    echo $foo
    ```
```

**Comment by Shougo** [comment]
https://github.com/Shougo/unite-outline/blob/master/autoload/unite/sources/outline/defaults/markdown.vim

Pull request is wellcome.

**Comment by KabbAmine** [comment]
#67 solves the issue, thanks to @thinca :smiley:
