### ISSUE TITLE
"Funcref required" during initialization

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/unite-outline#69]
:Unite outline
```
[unite.vim] /home/.../.vim/bundle/unite-outline/autoload/unite/sources/outline/modules/util.vim, line 56
[unite.vim] Vim(call):E718: Funcref required
[unite.vim] Error occurred in source initialization!
[unite.vim] Source name is /home/.../.vim/bundle/unite-outline/autoload/unite/sources/outline.vim
[unite.vim] Invalid source name "outline" is detected.
[unite.vim] unite.vim: Invalid source
```

Switching order of Util_get_indent_level and Util_get_indent_level makes the error occur at the first "call s:Util.function(...)".

Regretfully, VimL isn't exactly my cup of tea, so I cannot debug this myself.

unite: 282486e981c5027a8
unite-outline: 5b14dd651b7d4
vim: 7.4.1583

**Comment by Shougo** [comment]
I cannot reproduce it in Vim 7.4.1721.
Your Vim is too old.
Please update to latest Vim.

**Comment by kshpytsya** [comment]
Indeed, non reproducible with vim from git (7.4.1724).
Rhetorically: my version (which is the freshest in Gentoo/unstable as of today) was less than a month old, which one could only call "too old" only in a tongue-in-cheek manner, for such a mature piece of software as vim.
Thank you for your great piece of work.

**Comment by Shougo** [comment]
> Rhetorically: my version (which is the freshest in Gentoo/unstable as of today) was less than a month old, which one could call "too old" only in a tongue-in-cheek manner, for such a mature piece of software as vim.

"Too old" is true for current development speed of Vim.

**Comment by Shougo** [comment]
You may mind the my "too old version".
This is not the attack or joke.
You may think Gentoo HEAD Vim is stable version.
But it is not(It is same in Arch Vim too).
I don't know why Arch and Gentoo maintainers choose the broken revisions...

**Comment by kshpytsya** [comment]
No offence taken. I have just switched to so called "live ebuild" for vim which built from upstream's HEAD. If bugs are there to be, I choose to have fresh ones.
