### ISSUE TITLE
Can unite-outline work with Denite?

### ISSUE THREAD

**Issue by Vayn** [Shougo/unite-outline#77]
I don't know how to use this plugin with Denite. Does anyone find the right way?

**Comment by Shougo** [comment]
`Denite unite:outline`

**Comment by Vayn** [comment]
Thanks! This command is not described in the documentation.

**Comment by Shougo** [comment]
Because it is unite.vim feature.

**Comment by Shougo** [comment]
```
Q: I want to use unite source in denite.

A: You can use |unite-denite-source-unite| for it. >
	Denite unite:file
Note: unite installation is needed.
```

**Comment by Vayn** [comment]
Yes, I found I must install both Denite and Unite...

**Comment by Shougo** [comment]
Yes.  Unite-outline uses unite's feature.
No magic is here.

**Comment by Vayn** [comment]
Haha, thanks for the explanation. It is like different versions of .NET Framework.

**Comment by hungrybirder** [comment]
> `Denite unite:outline`

But this command output is not the same as `:Unite outline` output.

I like the `Unite: outline` output. 

Is there a way to keep the original output layout by using `Denite`?

**Comment by Shougo** [comment]
Unfortunately, nothing.
