### ISSUE TITLE
add outline to python

### ISSUE THREAD

**Issue by fab6** [Shougo/unite-outline#82]
Hi,

could you point me to documentation or give me a hint how to  add new outline "keywords"?
E.g. within Python, I would like to jump to certain comments.
The comments would start like this:
#- SEC:Tst
and the outline could show it like: SEC:Tst
Does this work?
Thanks!

**Comment by Shougo** [comment]
You can see the other implementation.

https://github.com/Shougo/unite-outline/tree/master/autoload/unite/sources/outline/defaults

**Comment by Shougo** [comment]
And Python support is already implemented.
https://github.com/Shougo/unite-outline/blob/master/autoload/unite/sources/outline/defaults/python.vim

**Comment by fab6** [comment]
Hi, ok, I saw the python implementation, but I understood, that this mainly looks for def and class and could not figure out how to adjust it for the above example... I will look again. Thanks!

**Comment by Shougo** [comment]
> Hi, ok, I saw the python implementation, but I understood, that this mainly looks for def and class and could not figure out how to adjust it for the above example... I will look again. Thanks!

Yes.  But you can extend it.

**Comment by fab6** [comment]
You are right, I will look into the other as well and look if I understand it.
